# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

ev_population:
  outputs:

    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'host.docker.internal') }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DBNAME', 'postgres') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'analytics') }}"
      threads: 4

  target: dev
