# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

ev_population:
  outputs:

    dev:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      port: 5432
      dbname: {{ env_var('POSTGRES_DBNAME') }}
      schema: {{ env_var('POSTGRES_SCHEMA') }}
      threads: 4

  target: dev
